$(asctime)s ERROR: Exception on /edit_profile [POST] [in $(pathname)s:1761]
Traceback (most recent call last):
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/routes.py", line 93, in edit_profile
    if form.validate_on_submit():
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/forms.py", line 41, in validate_username
    if user is not None:
UnboundLocalError: local variable 'user' referenced before assignment
$(asctime)s INFO: Jungo Jungo startup [in $(pathname)s:45]
$(asctime)s ERROR: Exception on /edit_profile [POST] [in $(pathname)s:1761]
Traceback (most recent call last):
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/routes.py", line 93, in edit_profile
    if form.validate_on_submit():
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/forms.py", line 41, in validate_username
    if user is not None:
UnboundLocalError: local variable 'user' referenced before assignment
$(asctime)s ERROR: Exception on /explore [GET] [in $(pathname)s:1761]
Traceback (most recent call last):
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/routes.py", line 139, in explore
    return render_template('index.html',title='Explore', posts=posts)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lhy/Project-Altair_Jungo_Jungo/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/templates/index.html", line 20, in block "content"
    {% include '_post.html' %}
  File "/home/lhy/Project-Altair_Jungo_Jungo/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
$(asctime)s INFO: Jungo Jungo startup [in $(pathname)s:45]
